blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://github.com/solidusio/solidus/discussions?discussions_q=category%3AIdeas
    about: Suggest an idea for this project
  - name: Troubleshooting
    url: https://github.com/solidusio/solidus/discussions?discussions_q=category%3ATroubleshooting
    about: Ask the community for help
